--*******FILL-IN TABLES WITH TEST DATA****************************
-- FILL-IN EMPLOYEE_ROLES TABLE ------------------------------
TRUNCATE TABLE ZOO.EMPLOYEE_ROLES CASCADE;
INSERT INTO ZOO.EMPLOYEE_ROLES(TITLE) VALUES
('EMPLOYEE'),
('ADMIN'),
('MANAGER');

-- FILL-IN EMPLOYEE TABLE ------------------------------
TRUNCATE TABLE ZOO.EMPLOYEES CASCADE;
INSERT INTO ZOO.EMPLOYEES(FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES
('IGOR', 'TSVETKOFF', 'ITSV@GMAIL.COM', 'DFBDBR3654F'),
('BOHDAN', 'CHERNIAKH', 'B.CHERNIAKH@GMAIL.COM', 'S43TFDDSV'),
('ANDRII', 'ABRAMOV', 'A.ABRAMOV@GMAIL.COM', 'DG46IQA')
/* -- UNCOMMENT TO CHECK INVALID INPUT VALIDATION
,('WRONG', 'EMAIL', 'DGMAIL.COM', 'DFR4F'), -- WRONG EMAIL (NO '@')
('ANDRII', 'ABRAMOV', 'A.ABRAMOV@GMAIL.COM', 'DG46IQA'), -- DUPLICATE EMAIL
*/
;

-- FILL-IN EMPLOYEE_ROLE_MAPPING ------------------------------
TRUNCATE TABLE ZOO.EMPLOYEE_ROLE_MAPPING CASCADE;
INSERT INTO ZOO.EMPLOYEE_ROLE_MAPPING(EMPLOYEE_ID, ROLE_ID) VALUES
((SELECT ID FROM ZOO.EMPLOYEES WHERE EMAIL='ITSV@GMAIL.COM'), 
	(SELECT ID FROM ZOO.EMPLOYEE_ROLES WHERE TITLE='MANAGER')),
((SELECT ID FROM ZOO.EMPLOYEES WHERE EMAIL='ITSV@GMAIL.COM'), 
	(SELECT ID FROM ZOO.EMPLOYEE_ROLES WHERE TITLE='EMPLOYEE')),
((SELECT ID FROM ZOO.EMPLOYEES WHERE EMAIL='B.CHERNIAKH@GMAIL.COM'), 
	(SELECT ID FROM ZOO.EMPLOYEE_ROLES WHERE TITLE='EMPLOYEE')
	);

-- FILL-IN WAREHOUSE
INSERT INTO ZOO.WAREHOUSE(SUPPLY_NAME, AMOUNT) VALUES
('MEDICINE', 100),
('FOOD', 100)
-- , ('FOOD2', -4) -- ERROR (VALUES < 0)
;

-- FILL-IN TASK_TYPES
TRUNCATE TABLE ZOO.TASK_TYPES CASCADE;
INSERT INTO ZOO.TASK_TYPES(TYPE) VALUES
('FEED ANIMALS'),
('HEALTH INSPECTION');

SELECT * FROM ZOO.WAREHOUSE;